name: Continuous Integration

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]

jobs:
  web-ci:
    name: Web App CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-size: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Run Web Linter
        run: npm run lint

      - name: Build Web App
        run: npm run build

  mobile-ci:
    name: Mobile App CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.19.x'
          channel: 'stable'
          cache: true

      - name: Get Pub Dependencies
        run: |
          cd apps/mobile
          flutter pub get

      - name: Check Formatting
        run: |
          cd apps/mobile
          dart format --set-exit-if-changed .

      - name: Run Dart Analyzer
        run: |
          cd apps/mobile
          flutter analyze
